owner: thulab
repo: anylearn-status

runner: 10-101-67-15

assignees:
  - phamour

user-agent: phamour

sites:
  - name: Anylearn
    url: https://anylearn.nelbds.cn
    icon: https://anylearn.nelbds.cn/favicon.ico
    __dangerous__disable_verify_peer: true

status-website:
  baseUrl: /anylearn-status
  logoUrl: https://anylearn.nelbds.cn/img/logo-long.8b317769.png
  name: Anylearn Status Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
