owner: thulab
repo: anylearn-status

# runner: thu419-1

assignees:
  - phamour

user-agent: phamour

sites:
  - name: Anylearn
    url: https://anylearn.nelbds.cn/
    icon: https://anylearn.nelbds.cn/favicon.ico

status-website:
  baseUrl: /anylearn-status
  logoUrl: https://anylearn.nelbds.cn/img/logo-long.8b317769.png
  name: Anylearn Status Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
